/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AchieveRouteImport } from './routes/achieve'
import { Route as AskRouteImport } from './routes/ask'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as JoinRouteImport } from './routes/join'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as StructureRouteImport } from './routes/structure'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WhyItMattersRouteImport } from './routes/why-it-matters'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AboutFaqRouteImport } from './routes/about/faq'
import { Route as AboutOurStoryRouteImport } from './routes/about/our-story'
import { Route as AboutWhatWeDoRouteImport } from './routes/about/what-we-do'
import { Route as GovernanceIndexRouteImport } from './routes/governance/index'
import { Route as GovernanceCodeOfConductRouteImport } from './routes/governance/code-of-conduct'
import { Route as GovernanceFounderRouteImport } from './routes/governance/founder'
import { Route as GovernancePrivacyRouteImport } from './routes/governance/privacy'
import { Route as GovernanceSafeguardingRouteImport } from './routes/governance/safeguarding'
import { Route as GovernanceSponsorshipRouteImport } from './routes/governance/sponsorship'
import { Route as GovernanceTransparencyRouteImport } from './routes/governance/transparency'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as InsightsCanYouJoinArmyWithDyslexiaUkRouteImport } from './routes/insights/can-you-join-army-with-dyslexia-uk'
import { Route as InsightsCanYouJoinNavyWithDyslexiaUkRouteImport } from './routes/insights/can-you-join-navy-with-dyslexia-uk'
import { Route as InsightsCanYouJoinRafWithDyslexiaUkRouteImport } from './routes/insights/can-you-join-raf-with-dyslexia-uk'
import { Route as InsightsDoINeedToDeclareDyslexiaWhenJoiningTheMilitaryUkRouteImport } from './routes/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk'
import { Route as InsightsIsDyslexiaABarrierInTheMilitaryUkRouteImport } from './routes/insights/is-dyslexia-a-barrier-in-the-military-uk'
import { Route as InsightsJsp822VsEqualityActDyslexiaMilitaryVsCivilianUkRouteImport } from './routes/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk'
import { Route as InsightsNeurodiversityInTheModUkRouteImport } from './routes/insights/neurodiversity-in-the-mod-uk'
import { Route as InsightsServingWithDyslexiaInTheArmyUkRouteImport } from './routes/insights/serving-with-dyslexia-in-the-army-uk'
import { Route as InsightsWhatHappensIfDyslexiaIsIdentifiedDuringServiceUkRouteImport } from './routes/insights/what-happens-if-dyslexia-is-identified-during-service-uk'
import { Route as InsightsWhatSupportIsAvailableForDyslexiaInTheMilitaryUkRouteImport } from './routes/insights/what-support-is-available-for-dyslexia-in-the-military-uk'
import { Route as LivedExperiencesIndexRouteImport } from './routes/lived-experiences/index'
import { Route as LivedExperiencesLisaHodgeCivilServantRouteImport } from './routes/lived-experiences/lisa-hodge-civil-servant'
import { Route as LivedExperiencesStaffSergeantKirkDavisBritishArmyRouteImport } from './routes/lived-experiences/staff-sergeant-kirk-davis-british-army'
import { Route as LivedExperiencesSymonSmithBritishArmyVeteranRouteImport } from './routes/lived-experiences/symon-smith-british-army-veteran'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AchieveRoute = AchieveRouteImport.update({
  id: '/achieve',
  path: '/achieve',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureRoute = StructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyItMattersRoute = WhyItMattersRouteImport.update({
  id: '/why-it-matters',
  path: '/why-it-matters',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFaqRoute = AboutFaqRouteImport.update({
  id: '/about/faq',
  path: '/about/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurStoryRoute = AboutOurStoryRouteImport.update({
  id: '/about/our-story',
  path: '/about/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutWhatWeDoRoute = AboutWhatWeDoRouteImport.update({
  id: '/about/what-we-do',
  path: '/about/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceIndexRoute = GovernanceIndexRouteImport.update({
  id: '/governance/',
  path: '/governance/',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceCodeOfConductRoute = GovernanceCodeOfConductRouteImport.update({
  id: '/governance/code-of-conduct',
  path: '/governance/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceFounderRoute = GovernanceFounderRouteImport.update({
  id: '/governance/founder',
  path: '/governance/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernancePrivacyRoute = GovernancePrivacyRouteImport.update({
  id: '/governance/privacy',
  path: '/governance/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceSafeguardingRoute = GovernanceSafeguardingRouteImport.update({
  id: '/governance/safeguarding',
  path: '/governance/safeguarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceSponsorshipRoute = GovernanceSponsorshipRouteImport.update({
  id: '/governance/sponsorship',
  path: '/governance/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceTransparencyRoute = GovernanceTransparencyRouteImport.update({
  id: '/governance/transparency',
  path: '/governance/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsCanYouJoinArmyWithDyslexiaUkRoute =
  InsightsCanYouJoinArmyWithDyslexiaUkRouteImport.update({
    id: '/insights/can-you-join-army-with-dyslexia-uk',
    path: '/insights/can-you-join-army-with-dyslexia-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsCanYouJoinNavyWithDyslexiaUkRoute =
  InsightsCanYouJoinNavyWithDyslexiaUkRouteImport.update({
    id: '/insights/can-you-join-navy-with-dyslexia-uk',
    path: '/insights/can-you-join-navy-with-dyslexia-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsCanYouJoinRafWithDyslexiaUkRoute =
  InsightsCanYouJoinRafWithDyslexiaUkRouteImport.update({
    id: '/insights/can-you-join-raf-with-dyslexia-uk',
    path: '/insights/can-you-join-raf-with-dyslexia-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsDoINeedToDeclareDyslexiaWhenJoiningTheMilitaryUkRoute =
  InsightsDoINeedToDeclareDyslexiaWhenJoiningTheMilitaryUkRouteImport.update({
    id: '/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk',
    path: '/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsIsDyslexiaABarrierInTheMilitaryUkRoute =
  InsightsIsDyslexiaABarrierInTheMilitaryUkRouteImport.update({
    id: '/insights/is-dyslexia-a-barrier-in-the-military-uk',
    path: '/insights/is-dyslexia-a-barrier-in-the-military-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsJsp822VsEqualityActDyslexiaMilitaryVsCivilianUkRoute =
  InsightsJsp822VsEqualityActDyslexiaMilitaryVsCivilianUkRouteImport.update({
    id: '/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk',
    path: '/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsNeurodiversityInTheModUkRoute =
  InsightsNeurodiversityInTheModUkRouteImport.update({
    id: '/insights/neurodiversity-in-the-mod-uk',
    path: '/insights/neurodiversity-in-the-mod-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsServingWithDyslexiaInTheArmyUkRoute =
  InsightsServingWithDyslexiaInTheArmyUkRouteImport.update({
    id: '/insights/serving-with-dyslexia-in-the-army-uk',
    path: '/insights/serving-with-dyslexia-in-the-army-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsWhatHappensIfDyslexiaIsIdentifiedDuringServiceUkRoute =
  InsightsWhatHappensIfDyslexiaIsIdentifiedDuringServiceUkRouteImport.update({
    id: '/insights/what-happens-if-dyslexia-is-identified-during-service-uk',
    path: '/insights/what-happens-if-dyslexia-is-identified-during-service-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsWhatSupportIsAvailableForDyslexiaInTheMilitaryUkRoute =
  InsightsWhatSupportIsAvailableForDyslexiaInTheMilitaryUkRouteImport.update({
    id: '/insights/what-support-is-available-for-dyslexia-in-the-military-uk',
    path: '/insights/what-support-is-available-for-dyslexia-in-the-military-uk',
    getParentRoute: () => rootRouteImport,
  } as any)
const LivedExperiencesIndexRoute = LivedExperiencesIndexRouteImport.update({
  id: '/lived-experiences/',
  path: '/lived-experiences/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivedExperiencesLisaHodgeCivilServantRoute =
  LivedExperiencesLisaHodgeCivilServantRouteImport.update({
    id: '/lived-experiences/lisa-hodge-civil-servant',
    path: '/lived-experiences/lisa-hodge-civil-servant',
    getParentRoute: () => rootRouteImport,
  } as any)
const LivedExperiencesStaffSergeantKirkDavisBritishArmyRoute =
  LivedExperiencesStaffSergeantKirkDavisBritishArmyRouteImport.update({
    id: '/lived-experiences/staff-sergeant-kirk-davis-british-army',
    path: '/lived-experiences/staff-sergeant-kirk-davis-british-army',
    getParentRoute: () => rootRouteImport,
  } as any)
const LivedExperiencesSymonSmithBritishArmyVeteranRoute =
  LivedExperiencesSymonSmithBritishArmyVeteranRouteImport.update({
    id: '/lived-experiences/symon-smith-british-army-veteran',
    path: '/lived-experiences/symon-smith-british-army-veteran',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/achieve': typeof AchieveRoute
  '/ask': typeof AskRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/join': typeof JoinRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/structure': typeof StructureRoute
  '/support': typeof SupportRoute
  '/why-it-matters': typeof WhyItMattersRoute
  '/about/faq': typeof AboutFaqRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/what-we-do': typeof AboutWhatWeDoRoute
  '/governance/code-of-conduct': typeof GovernanceCodeOfConductRoute
  '/governance/founder': typeof GovernanceFounderRoute
  '/governance/privacy': typeof GovernancePrivacyRoute
  '/governance/safeguarding': typeof GovernanceSafeguardingRoute
  '/governance/sponsorship': typeof GovernanceSponsorshipRoute
  '/governance/transparency': typeof GovernanceTransparencyRoute
  '/insights/can-you-join-army-with-dyslexia-uk': typeof InsightsCanYouJoinArmyWithDyslexiaUkRoute
  '/insights/can-you-join-navy-with-dyslexia-uk': typeof InsightsCanYouJoinNavyWithDyslexiaUkRoute
  '/insights/can-you-join-raf-with-dyslexia-uk': typeof InsightsCanYouJoinRafWithDyslexiaUkRoute
  '/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk': typeof InsightsDoINeedToDeclareDyslexiaWhenJoiningTheMilitaryUkRoute
  '/insights/is-dyslexia-a-barrier-in-the-military-uk': typeof InsightsIsDyslexiaABarrierInTheMilitaryUkRoute
  '/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk': typeof InsightsJsp822VsEqualityActDyslexiaMilitaryVsCivilianUkRoute
  '/insights/neurodiversity-in-the-mod-uk': typeof InsightsNeurodiversityInTheModUkRoute
  '/insights/serving-with-dyslexia-in-the-army-uk': typeof InsightsServingWithDyslexiaInTheArmyUkRoute
  '/insights/what-happens-if-dyslexia-is-identified-during-service-uk': typeof InsightsWhatHappensIfDyslexiaIsIdentifiedDuringServiceUkRoute
  '/insights/what-support-is-available-for-dyslexia-in-the-military-uk': typeof InsightsWhatSupportIsAvailableForDyslexiaInTheMilitaryUkRoute
  '/lived-experiences/lisa-hodge-civil-servant': typeof LivedExperiencesLisaHodgeCivilServantRoute
  '/lived-experiences/staff-sergeant-kirk-davis-british-army': typeof LivedExperiencesStaffSergeantKirkDavisBritishArmyRoute
  '/lived-experiences/symon-smith-british-army-veteran': typeof LivedExperiencesSymonSmithBritishArmyVeteranRoute
  '/about/': typeof AboutIndexRoute
  '/governance/': typeof GovernanceIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/lived-experiences/': typeof LivedExperiencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/achieve': typeof AchieveRoute
  '/ask': typeof AskRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/join': typeof JoinRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/structure': typeof StructureRoute
  '/support': typeof SupportRoute
  '/why-it-matters': typeof WhyItMattersRoute
  '/about/faq': typeof AboutFaqRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/what-we-do': typeof AboutWhatWeDoRoute
  '/governance/code-of-conduct': typeof GovernanceCodeOfConductRoute
  '/governance/founder': typeof GovernanceFounderRoute
  '/governance/privacy': typeof GovernancePrivacyRoute
  '/governance/safeguarding': typeof GovernanceSafeguardingRoute
  '/governance/sponsorship': typeof GovernanceSponsorshipRoute
  '/governance/transparency': typeof GovernanceTransparencyRoute
  '/insights/can-you-join-army-with-dyslexia-uk': typeof InsightsCanYouJoinArmyWithDyslexiaUkRoute
  '/insights/can-you-join-navy-with-dyslexia-uk': typeof InsightsCanYouJoinNavyWithDyslexiaUkRoute
  '/insights/can-you-join-raf-with-dyslexia-uk': typeof InsightsCanYouJoinRafWithDyslexiaUkRoute
  '/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk': typeof InsightsDoINeedToDeclareDyslexiaWhenJoiningTheMilitaryUkRoute
  '/insights/is-dyslexia-a-barrier-in-the-military-uk': typeof InsightsIsDyslexiaABarrierInTheMilitaryUkRoute
  '/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk': typeof InsightsJsp822VsEqualityActDyslexiaMilitaryVsCivilianUkRoute
  '/insights/neurodiversity-in-the-mod-uk': typeof InsightsNeurodiversityInTheModUkRoute
  '/insights/serving-with-dyslexia-in-the-army-uk': typeof InsightsServingWithDyslexiaInTheArmyUkRoute
  '/insights/what-happens-if-dyslexia-is-identified-during-service-uk': typeof InsightsWhatHappensIfDyslexiaIsIdentifiedDuringServiceUkRoute
  '/insights/what-support-is-available-for-dyslexia-in-the-military-uk': typeof InsightsWhatSupportIsAvailableForDyslexiaInTheMilitaryUkRoute
  '/lived-experiences/lisa-hodge-civil-servant': typeof LivedExperiencesLisaHodgeCivilServantRoute
  '/lived-experiences/staff-sergeant-kirk-davis-british-army': typeof LivedExperiencesStaffSergeantKirkDavisBritishArmyRoute
  '/lived-experiences/symon-smith-british-army-veteran': typeof LivedExperiencesSymonSmithBritishArmyVeteranRoute
  '/about': typeof AboutIndexRoute
  '/governance': typeof GovernanceIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/lived-experiences': typeof LivedExperiencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/achieve': typeof AchieveRoute
  '/ask': typeof AskRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/join': typeof JoinRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/structure': typeof StructureRoute
  '/support': typeof SupportRoute
  '/why-it-matters': typeof WhyItMattersRoute
  '/about/faq': typeof AboutFaqRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/what-we-do': typeof AboutWhatWeDoRoute
  '/governance/code-of-conduct': typeof GovernanceCodeOfConductRoute
  '/governance/founder': typeof GovernanceFounderRoute
  '/governance/privacy': typeof GovernancePrivacyRoute
  '/governance/safeguarding': typeof GovernanceSafeguardingRoute
  '/governance/sponsorship': typeof GovernanceSponsorshipRoute
  '/governance/transparency': typeof GovernanceTransparencyRoute
  '/insights/can-you-join-army-with-dyslexia-uk': typeof InsightsCanYouJoinArmyWithDyslexiaUkRoute
  '/insights/can-you-join-navy-with-dyslexia-uk': typeof InsightsCanYouJoinNavyWithDyslexiaUkRoute
  '/insights/can-you-join-raf-with-dyslexia-uk': typeof InsightsCanYouJoinRafWithDyslexiaUkRoute
  '/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk': typeof InsightsDoINeedToDeclareDyslexiaWhenJoiningTheMilitaryUkRoute
  '/insights/is-dyslexia-a-barrier-in-the-military-uk': typeof InsightsIsDyslexiaABarrierInTheMilitaryUkRoute
  '/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk': typeof InsightsJsp822VsEqualityActDyslexiaMilitaryVsCivilianUkRoute
  '/insights/neurodiversity-in-the-mod-uk': typeof InsightsNeurodiversityInTheModUkRoute
  '/insights/serving-with-dyslexia-in-the-army-uk': typeof InsightsServingWithDyslexiaInTheArmyUkRoute
  '/insights/what-happens-if-dyslexia-is-identified-during-service-uk': typeof InsightsWhatHappensIfDyslexiaIsIdentifiedDuringServiceUkRoute
  '/insights/what-support-is-available-for-dyslexia-in-the-military-uk': typeof InsightsWhatSupportIsAvailableForDyslexiaInTheMilitaryUkRoute
  '/lived-experiences/lisa-hodge-civil-servant': typeof LivedExperiencesLisaHodgeCivilServantRoute
  '/lived-experiences/staff-sergeant-kirk-davis-british-army': typeof LivedExperiencesStaffSergeantKirkDavisBritishArmyRoute
  '/lived-experiences/symon-smith-british-army-veteran': typeof LivedExperiencesSymonSmithBritishArmyVeteranRoute
  '/about/': typeof AboutIndexRoute
  '/governance/': typeof GovernanceIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/lived-experiences/': typeof LivedExperiencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/achieve'
    | '/ask'
    | '/community'
    | '/contact'
    | '/ecosystem'
    | '/join'
    | '/partner'
    | '/privacy'
    | '/resources'
    | '/structure'
    | '/support'
    | '/why-it-matters'
    | '/about/faq'
    | '/about/our-story'
    | '/about/what-we-do'
    | '/governance/code-of-conduct'
    | '/governance/founder'
    | '/governance/privacy'
    | '/governance/safeguarding'
    | '/governance/sponsorship'
    | '/governance/transparency'
    | '/insights/can-you-join-army-with-dyslexia-uk'
    | '/insights/can-you-join-navy-with-dyslexia-uk'
    | '/insights/can-you-join-raf-with-dyslexia-uk'
    | '/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk'
    | '/insights/is-dyslexia-a-barrier-in-the-military-uk'
    | '/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk'
    | '/insights/neurodiversity-in-the-mod-uk'
    | '/insights/serving-with-dyslexia-in-the-army-uk'
    | '/insights/what-happens-if-dyslexia-is-identified-during-service-uk'
    | '/insights/what-support-is-available-for-dyslexia-in-the-military-uk'
    | '/lived-experiences/lisa-hodge-civil-servant'
    | '/lived-experiences/staff-sergeant-kirk-davis-british-army'
    | '/lived-experiences/symon-smith-british-army-veteran'
    | '/about/'
    | '/governance/'
    | '/insights/'
    | '/lived-experiences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/achieve'
    | '/ask'
    | '/community'
    | '/contact'
    | '/ecosystem'
    | '/join'
    | '/partner'
    | '/privacy'
    | '/resources'
    | '/structure'
    | '/support'
    | '/why-it-matters'
    | '/about/faq'
    | '/about/our-story'
    | '/about/what-we-do'
    | '/governance/code-of-conduct'
    | '/governance/founder'
    | '/governance/privacy'
    | '/governance/safeguarding'
    | '/governance/sponsorship'
    | '/governance/transparency'
    | '/insights/can-you-join-army-with-dyslexia-uk'
    | '/insights/can-you-join-navy-with-dyslexia-uk'
    | '/insights/can-you-join-raf-with-dyslexia-uk'
    | '/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk'
    | '/insights/is-dyslexia-a-barrier-in-the-military-uk'
    | '/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk'
    | '/insights/neurodiversity-in-the-mod-uk'
    | '/insights/serving-with-dyslexia-in-the-army-uk'
    | '/insights/what-happens-if-dyslexia-is-identified-during-service-uk'
    | '/insights/what-support-is-available-for-dyslexia-in-the-military-uk'
    | '/lived-experiences/lisa-hodge-civil-servant'
    | '/lived-experiences/staff-sergeant-kirk-davis-british-army'
    | '/lived-experiences/symon-smith-british-army-veteran'
    | '/about'
    | '/governance'
    | '/insights'
    | '/lived-experiences'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/achieve'
    | '/ask'
    | '/community'
    | '/contact'
    | '/ecosystem'
    | '/join'
    | '/partner'
    | '/privacy'
    | '/resources'
    | '/structure'
    | '/support'
    | '/why-it-matters'
    | '/about/faq'
    | '/about/our-story'
    | '/about/what-we-do'
    | '/governance/code-of-conduct'
    | '/governance/founder'
    | '/governance/privacy'
    | '/governance/safeguarding'
    | '/governance/sponsorship'
    | '/governance/transparency'
    | '/insights/can-you-join-army-with-dyslexia-uk'
    | '/insights/can-you-join-navy-with-dyslexia-uk'
    | '/insights/can-you-join-raf-with-dyslexia-uk'
    | '/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk'
    | '/insights/is-dyslexia-a-barrier-in-the-military-uk'
    | '/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk'
    | '/insights/neurodiversity-in-the-mod-uk'
    | '/insights/serving-with-dyslexia-in-the-army-uk'
    | '/insights/what-happens-if-dyslexia-is-identified-during-service-uk'
    | '/insights/what-support-is-available-for-dyslexia-in-the-military-uk'
    | '/lived-experiences/lisa-hodge-civil-servant'
    | '/lived-experiences/staff-sergeant-kirk-davis-british-army'
    | '/lived-experiences/symon-smith-british-army-veteran'
    | '/about/'
    | '/governance/'
    | '/insights/'
    | '/lived-experiences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AchieveRoute: typeof AchieveRoute
  AskRoute: typeof AskRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  EcosystemRoute: typeof EcosystemRoute
  JoinRoute: typeof JoinRoute
  PartnerRoute: typeof PartnerRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  StructureRoute: typeof StructureRoute
  SupportRoute: typeof SupportRoute
  WhyItMattersRoute: typeof WhyItMattersRoute
  AboutFaqRoute: typeof AboutFaqRoute
  AboutOurStoryRoute: typeof AboutOurStoryRoute
  AboutWhatWeDoRoute: typeof AboutWhatWeDoRoute
  GovernanceCodeOfConductRoute: typeof GovernanceCodeOfConductRoute
  GovernanceFounderRoute: typeof GovernanceFounderRoute
  GovernancePrivacyRoute: typeof GovernancePrivacyRoute
  GovernanceSafeguardingRoute: typeof GovernanceSafeguardingRoute
  GovernanceSponsorshipRoute: typeof GovernanceSponsorshipRoute
  GovernanceTransparencyRoute: typeof GovernanceTransparencyRoute
  InsightsCanYouJoinArmyWithDyslexiaUkRoute: typeof InsightsCanYouJoinArmyWithDyslexiaUkRoute
  InsightsCanYouJoinNavyWithDyslexiaUkRoute: typeof InsightsCanYouJoinNavyWithDyslexiaUkRoute
  InsightsCanYouJoinRafWithDyslexiaUkRoute: typeof InsightsCanYouJoinRafWithDyslexiaUkRoute
  InsightsDoINeedToDeclareDyslexiaWhenJoiningTheMilitaryUkRoute: typeof InsightsDoINeedToDeclareDyslexiaWhenJoiningTheMilitaryUkRoute
  InsightsIsDyslexiaABarrierInTheMilitaryUkRoute: typeof InsightsIsDyslexiaABarrierInTheMilitaryUkRoute
  InsightsJsp822VsEqualityActDyslexiaMilitaryVsCivilianUkRoute: typeof InsightsJsp822VsEqualityActDyslexiaMilitaryVsCivilianUkRoute
  InsightsNeurodiversityInTheModUkRoute: typeof InsightsNeurodiversityInTheModUkRoute
  InsightsServingWithDyslexiaInTheArmyUkRoute: typeof InsightsServingWithDyslexiaInTheArmyUkRoute
  InsightsWhatHappensIfDyslexiaIsIdentifiedDuringServiceUkRoute: typeof InsightsWhatHappensIfDyslexiaIsIdentifiedDuringServiceUkRoute
  InsightsWhatSupportIsAvailableForDyslexiaInTheMilitaryUkRoute: typeof InsightsWhatSupportIsAvailableForDyslexiaInTheMilitaryUkRoute
  LivedExperiencesLisaHodgeCivilServantRoute: typeof LivedExperiencesLisaHodgeCivilServantRoute
  LivedExperiencesStaffSergeantKirkDavisBritishArmyRoute: typeof LivedExperiencesStaffSergeantKirkDavisBritishArmyRoute
  LivedExperiencesSymonSmithBritishArmyVeteranRoute: typeof LivedExperiencesSymonSmithBritishArmyVeteranRoute
  AboutIndexRoute: typeof AboutIndexRoute
  GovernanceIndexRoute: typeof GovernanceIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  LivedExperiencesIndexRoute: typeof LivedExperiencesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achieve': {
      id: '/achieve'
      path: '/achieve'
      fullPath: '/achieve'
      preLoaderRoute: typeof AchieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure': {
      id: '/structure'
      path: '/structure'
      fullPath: '/structure'
      preLoaderRoute: typeof StructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-it-matters': {
      id: '/why-it-matters'
      path: '/why-it-matters'
      fullPath: '/why-it-matters'
      preLoaderRoute: typeof WhyItMattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/faq': {
      id: '/about/faq'
      path: '/about/faq'
      fullPath: '/about/faq'
      preLoaderRoute: typeof AboutFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/our-story': {
      id: '/about/our-story'
      path: '/about/our-story'
      fullPath: '/about/our-story'
      preLoaderRoute: typeof AboutOurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/what-we-do': {
      id: '/about/what-we-do'
      path: '/about/what-we-do'
      fullPath: '/about/what-we-do'
      preLoaderRoute: typeof AboutWhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/': {
      id: '/governance/'
      path: '/governance'
      fullPath: '/governance/'
      preLoaderRoute: typeof GovernanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/code-of-conduct': {
      id: '/governance/code-of-conduct'
      path: '/governance/code-of-conduct'
      fullPath: '/governance/code-of-conduct'
      preLoaderRoute: typeof GovernanceCodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/founder': {
      id: '/governance/founder'
      path: '/governance/founder'
      fullPath: '/governance/founder'
      preLoaderRoute: typeof GovernanceFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/privacy': {
      id: '/governance/privacy'
      path: '/governance/privacy'
      fullPath: '/governance/privacy'
      preLoaderRoute: typeof GovernancePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/safeguarding': {
      id: '/governance/safeguarding'
      path: '/governance/safeguarding'
      fullPath: '/governance/safeguarding'
      preLoaderRoute: typeof GovernanceSafeguardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/sponsorship': {
      id: '/governance/sponsorship'
      path: '/governance/sponsorship'
      fullPath: '/governance/sponsorship'
      preLoaderRoute: typeof GovernanceSponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/transparency': {
      id: '/governance/transparency'
      path: '/governance/transparency'
      fullPath: '/governance/transparency'
      preLoaderRoute: typeof GovernanceTransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/can-you-join-army-with-dyslexia-uk': {
      id: '/insights/can-you-join-army-with-dyslexia-uk'
      path: '/insights/can-you-join-army-with-dyslexia-uk'
      fullPath: '/insights/can-you-join-army-with-dyslexia-uk'
      preLoaderRoute: typeof InsightsCanYouJoinArmyWithDyslexiaUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/can-you-join-navy-with-dyslexia-uk': {
      id: '/insights/can-you-join-navy-with-dyslexia-uk'
      path: '/insights/can-you-join-navy-with-dyslexia-uk'
      fullPath: '/insights/can-you-join-navy-with-dyslexia-uk'
      preLoaderRoute: typeof InsightsCanYouJoinNavyWithDyslexiaUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/can-you-join-raf-with-dyslexia-uk': {
      id: '/insights/can-you-join-raf-with-dyslexia-uk'
      path: '/insights/can-you-join-raf-with-dyslexia-uk'
      fullPath: '/insights/can-you-join-raf-with-dyslexia-uk'
      preLoaderRoute: typeof InsightsCanYouJoinRafWithDyslexiaUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk': {
      id: '/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk'
      path: '/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk'
      fullPath: '/insights/do-i-need-to-declare-dyslexia-when-joining-the-military-uk'
      preLoaderRoute: typeof InsightsDoINeedToDeclareDyslexiaWhenJoiningTheMilitaryUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/is-dyslexia-a-barrier-in-the-military-uk': {
      id: '/insights/is-dyslexia-a-barrier-in-the-military-uk'
      path: '/insights/is-dyslexia-a-barrier-in-the-military-uk'
      fullPath: '/insights/is-dyslexia-a-barrier-in-the-military-uk'
      preLoaderRoute: typeof InsightsIsDyslexiaABarrierInTheMilitaryUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk': {
      id: '/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk'
      path: '/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk'
      fullPath: '/insights/jsp822-vs-equality-act-dyslexia-military-vs-civilian-uk'
      preLoaderRoute: typeof InsightsJsp822VsEqualityActDyslexiaMilitaryVsCivilianUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/neurodiversity-in-the-mod-uk': {
      id: '/insights/neurodiversity-in-the-mod-uk'
      path: '/insights/neurodiversity-in-the-mod-uk'
      fullPath: '/insights/neurodiversity-in-the-mod-uk'
      preLoaderRoute: typeof InsightsNeurodiversityInTheModUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/serving-with-dyslexia-in-the-army-uk': {
      id: '/insights/serving-with-dyslexia-in-the-army-uk'
      path: '/insights/serving-with-dyslexia-in-the-army-uk'
      fullPath: '/insights/serving-with-dyslexia-in-the-army-uk'
      preLoaderRoute: typeof InsightsServingWithDyslexiaInTheArmyUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/what-happens-if-dyslexia-is-identified-during-service-uk': {
      id: '/insights/what-happens-if-dyslexia-is-identified-during-service-uk'
      path: '/insights/what-happens-if-dyslexia-is-identified-during-service-uk'
      fullPath: '/insights/what-happens-if-dyslexia-is-identified-during-service-uk'
      preLoaderRoute: typeof InsightsWhatHappensIfDyslexiaIsIdentifiedDuringServiceUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/what-support-is-available-for-dyslexia-in-the-military-uk': {
      id: '/insights/what-support-is-available-for-dyslexia-in-the-military-uk'
      path: '/insights/what-support-is-available-for-dyslexia-in-the-military-uk'
      fullPath: '/insights/what-support-is-available-for-dyslexia-in-the-military-uk'
      preLoaderRoute: typeof InsightsWhatSupportIsAvailableForDyslexiaInTheMilitaryUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lived-experiences/': {
      id: '/lived-experiences/'
      path: '/lived-experiences'
      fullPath: '/lived-experiences/'
      preLoaderRoute: typeof LivedExperiencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lived-experiences/lisa-hodge-civil-servant': {
      id: '/lived-experiences/lisa-hodge-civil-servant'
      path: '/lived-experiences/lisa-hodge-civil-servant'
      fullPath: '/lived-experiences/lisa-hodge-civil-servant'
      preLoaderRoute: typeof LivedExperiencesLisaHodgeCivilServantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lived-experiences/staff-sergeant-kirk-davis-british-army': {
      id: '/lived-experiences/staff-sergeant-kirk-davis-british-army'
      path: '/lived-experiences/staff-sergeant-kirk-davis-british-army'
      fullPath: '/lived-experiences/staff-sergeant-kirk-davis-british-army'
      preLoaderRoute: typeof LivedExperiencesStaffSergeantKirkDavisBritishArmyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lived-experiences/symon-smith-british-army-veteran': {
      id: '/lived-experiences/symon-smith-british-army-veteran'
      path: '/lived-experiences/symon-smith-british-army-veteran'
      fullPath: '/lived-experiences/symon-smith-british-army-veteran'
      preLoaderRoute: typeof LivedExperiencesSymonSmithBritishArmyVeteranRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AchieveRoute: AchieveRoute,
  AskRoute: AskRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  EcosystemRoute: EcosystemRoute,
  JoinRoute: JoinRoute,
  PartnerRoute: PartnerRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  StructureRoute: StructureRoute,
  SupportRoute: SupportRoute,
  WhyItMattersRoute: WhyItMattersRoute,
  AboutFaqRoute: AboutFaqRoute,
  AboutOurStoryRoute: AboutOurStoryRoute,
  AboutWhatWeDoRoute: AboutWhatWeDoRoute,
  GovernanceCodeOfConductRoute: GovernanceCodeOfConductRoute,
  GovernanceFounderRoute: GovernanceFounderRoute,
  GovernancePrivacyRoute: GovernancePrivacyRoute,
  GovernanceSafeguardingRoute: GovernanceSafeguardingRoute,
  GovernanceSponsorshipRoute: GovernanceSponsorshipRoute,
  GovernanceTransparencyRoute: GovernanceTransparencyRoute,
  InsightsCanYouJoinArmyWithDyslexiaUkRoute:
    InsightsCanYouJoinArmyWithDyslexiaUkRoute,
  InsightsCanYouJoinNavyWithDyslexiaUkRoute:
    InsightsCanYouJoinNavyWithDyslexiaUkRoute,
  InsightsCanYouJoinRafWithDyslexiaUkRoute:
    InsightsCanYouJoinRafWithDyslexiaUkRoute,
  InsightsDoINeedToDeclareDyslexiaWhenJoiningTheMilitaryUkRoute:
    InsightsDoINeedToDeclareDyslexiaWhenJoiningTheMilitaryUkRoute,
  InsightsIsDyslexiaABarrierInTheMilitaryUkRoute:
    InsightsIsDyslexiaABarrierInTheMilitaryUkRoute,
  InsightsJsp822VsEqualityActDyslexiaMilitaryVsCivilianUkRoute:
    InsightsJsp822VsEqualityActDyslexiaMilitaryVsCivilianUkRoute,
  InsightsNeurodiversityInTheModUkRoute: InsightsNeurodiversityInTheModUkRoute,
  InsightsServingWithDyslexiaInTheArmyUkRoute:
    InsightsServingWithDyslexiaInTheArmyUkRoute,
  InsightsWhatHappensIfDyslexiaIsIdentifiedDuringServiceUkRoute:
    InsightsWhatHappensIfDyslexiaIsIdentifiedDuringServiceUkRoute,
  InsightsWhatSupportIsAvailableForDyslexiaInTheMilitaryUkRoute:
    InsightsWhatSupportIsAvailableForDyslexiaInTheMilitaryUkRoute,
  LivedExperiencesLisaHodgeCivilServantRoute:
    LivedExperiencesLisaHodgeCivilServantRoute,
  LivedExperiencesStaffSergeantKirkDavisBritishArmyRoute:
    LivedExperiencesStaffSergeantKirkDavisBritishArmyRoute,
  LivedExperiencesSymonSmithBritishArmyVeteranRoute:
    LivedExperiencesSymonSmithBritishArmyVeteranRoute,
  AboutIndexRoute: AboutIndexRoute,
  GovernanceIndexRoute: GovernanceIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  LivedExperiencesIndexRoute: LivedExperiencesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
